//IZBRISI AKO NAKON DODAVANJE BAZE VISE NE TRIBA

export const blogs = [

    { title: 'CANDY-COATED FUN: IDEAS FOR CREATIVE AND DELICIOUS DESSERTS', author: 'Mary Morris', picture_path: 'candyc.svg', cta_text: 'If youre looking for a tasty way to make dessert time more fun, look no further! Try out these creative and delicious candy-coated ideas for a sweet treat that is sure to delight. Get creative in the kitchen and make your own candy-coated desserts today!', markdown_path: 'candyCoatedFun.md', banner_path: 'candycB.svg' },
    { title: 'COOKIE IDEAS FOR KIDS', author: 'Maria Clarkson', picture_path: 'kids.svg', cta_text: 'Try these fun and creative cookie ideas for your kids! Get creative in the kitchen and let their imaginations run wild with these delicious ideas. Let your kids pick their favorite cookie and get baking!', markdown_path: 'cookieForKids.md', banner_path: 'kidsB.svg' },
    { title: 'DECORATING TIPS FOR HOLIDAY COOKIES', author: 'Carla Hernandez', picture_path: 'decor.svg', cta_text: 'Ready to get your holiday baking underway? Try out these easy decorating tips for holiday cookies! From classic frosting to fun sprinkles, you are sure to make delicious treats your family will love. Get creative and experiment with different decorations to make your cookies stand out this holiday season!', markdown_path: 'decoratingTipsForHilidayCookies.md', banner_path: 'decorB.svg' },
    { title: 'FABULOUS MINT CANDIES', author: 'Jack Smith', picture_path: 'mint.svg', cta_text: 'Read a review about mint candies like you havve never tried before. Mint candies are the perfect combination of sweet and tangy, with a cool and refreshing flavor.', markdown_path: 'fabulousMintCandies.md', banner_path: 'mintB.svg' },
    { title: 'HER MAJESTY - MILK CHOCOLATE', author: 'John McCalister', picture_path: 'majestymilk.svg', cta_text: 'Try this delicious milk chocolate today! Indulge in a moment of pure bliss with our creamy and smooth milk chocolate. Enjoy the sweet, decadent flavor and treat yourself to a something special. Get yours now!', markdown_path: 'herMajestyMilkChocolate.md', banner_path: 'majestymilkB.svg' },
    { title: 'THE HISTORY OF CHOCOLATE: A JOURNEY FROM BEAN TO BAR AT YOUR LOCAL CHOCOLATE SHOP', author: 'Enzo Addams', picture_path: 'choco.svg', cta_text: 'Experience the sweet journey of chocolate and taste a delicious variety of chocolate bars your local chocolate shop has to offer! Explore the history of chocolate and savor the flavors of the past.', markdown_path: 'historyOfChocolate.md', banner_path: 'chocoB.svg' },
    { title: 'LOW-CALORIE SNACKS', author: 'LOW-CALORIE SNACKS', picture_path: 'lowCalorie.svg', cta_text: 'Enjoy wide selection of low-calorie sweets for guilt-free indulgence. Read this blog and find out which of them are in the top 5!', markdown_path: 'lowCalorieSnacks.md', banner_path: 'lowCalorieB.svg' },
    { title: 'DARK CHOCOLATE FOR ATHLETES', author: 'Mike Jackson', picture_path: 'dark.svg', cta_text: 'Try this sugar-free dark chocolate which is a delicious treat that is packed with antioxidants and has numerous health benefits.', markdown_path: 'sugarFreeDarkChocolate.md', banner_path: 'darkB.svg' },
    { title: 'THE BEST OF MILKA', author: 'Ann Thorne', picture_path: 'milka.svg', cta_text: 'We visited Germany and tried 10 different Milka chocolates. Which do you think impressed us the most?', markdown_path: 'theBestOfMilka.md', banner_path: 'milkaB.svg' },

];